In [1]:
import pandas as pd 
import numpy as np 
from pathlib import Path

In [2]:
spy_oct = pd.read_csv("spy_30x_202110.txt")
#spy_oct.to_csv("spy_30x_202110.csv", index=None)

In [3]:
spy_nov = pd.read_csv("spy_30x_202111.txt")
#spy_nov.to_csv("spy_30x_202111.csv", index=None)

C:\Users\aarch\AppData\Local\Temp\ipykernel_5980\1251898687.py:1: DtypeWarning: Columns (8,9,10,11,12,15,17,18,20,21,23,24,25,26,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  spy_nov = pd.read_csv("spy_30x_202111.txt")

In [4]:
spy_dec = pd.read_csv("spy_30x_202112.txt")
#spy_dec.to_csv("spy_30x_202112.csv", index=None)

C:\Users\aarch\AppData\Local\Temp\ipykernel_5980\1362792482.py:1: DtypeWarning: Columns (15,17,18,20,21,23,29) have mixed types. Specify dtype option on import or set low_memory=False.
  spy_dec = pd.read_csv("spy_30x_202112.txt")

In [5]:
spy_2021 = pd.concat([spy_oct, spy_nov, spy_dec], axis=0)

In [6]:
spy_2021.columns

Index(['[QUOTE_UNIXTIME]', ' [QUOTE_READTIME]', ' [QUOTE_DATE]',
       ' [QUOTE_TIME_HOURS]', ' [UNDERLYING_LAST]', ' [EXPIRE_DATE]',
       ' [EXPIRE_UNIX]', ' [DTE]', ' [C_DELTA]', ' [C_GAMMA]', ' [C_VEGA]',
       ' [C_THETA]', ' [C_RHO]', ' [C_IV]', ' [C_VOLUME]', ' [C_LAST]',
       ' [C_SIZE]', ' [C_BID]', ' [C_ASK]', ' [STRIKE]', ' [P_BID]',
       ' [P_ASK]', ' [P_SIZE]', ' [P_LAST]', ' [P_DELTA]', ' [P_GAMMA]',
       ' [P_VEGA]', ' [P_THETA]', ' [P_RHO]', ' [P_IV]', ' [P_VOLUME]',
       ' [STRIKE_DISTANCE]', ' [STRIKE_DISTANCE_PCT]'],
      dtype='object')

In [7]:
#spy_add = spy_2021.loc[' [STRIKE_DISTANCE]']

In [8]:
spy_2021.drop(columns = [' [P_BID]',' [P_ASK]', ' [P_SIZE]', ' [P_LAST]', ' [P_DELTA]', ' [P_GAMMA]',' [P_VEGA]', ' [P_THETA]', ' [P_RHO]', ' [P_IV]', ' [P_VOLUME]'], inplace = True, axis=1)

In [9]:
spy_2021.head()

,[QUOTE_UNIXTIME],[QUOTE_READTIME],[QUOTE_DATE],[QUOTE_TIME_HOURS],[UNDERLYING_LAST],[EXPIRE_DATE],[EXPIRE_UNIX],[DTE],[C_DELTA],[C_GAMMA],...,[C_RHO],[C_IV],[C_VOLUME],[C_LAST],[C_SIZE],[C_BID],[C_ASK],[STRIKE],[STRIKE_DISTANCE],[STRIKE_DISTANCE_PCT]
0,1633095010,2021-10-01 09:30,2021-10-01,9.5,431.04,2021-10-01,1633118400,0.27,0.895780,-0.000020,...,0.001140,7.629850,0.000000,194.650000,50 x 50,190.420000,191.740000,240.0,191.0,0.443
1,1633095010,2021-10-01 09:30,2021-10-01,9.5,431.04,2021-10-01,1633118400,0.27,1.000000,0.000000,...,0.000000,,,0.000000,66 x 66,185.180000,186.790000,245.0,186.0,0.432
2,1633095010,2021-10-01 09:30,2021-10-01,9.5,431.04,2021-10-01,1633118400,0.27,1.000000,0.000000,...,0.000000,,,0.000000,66 x 66,180.180000,181.790000,250.0,181.0,0.420
3,1633095010,2021-10-01 09:30,2021-10-01,9.5,431.04,2021-10-01,1633118400,0.27,0.902520,-0.000010,...,0.000370,6.615720,,0.000000,50 x 50,175.410000,176.730000,255.0,176.0,0.408
4,1633095010,2021-10-01 09:30,2021-10-01,9.5,431.04,2021-10-01,1633118400,0.27,0.904220,0.000030,...,0.000780,6.309530,1.000000,192.560000,50 x 50,170.420000,171.740000,260.0,171.0,0.397

In [10]:
spy_2021.rename(columns = {' [QUOTE_READTIME]': 'QUOTE_READTIME',' [UNDERLYING_LAST]': 'UNDERLYING_LAST', ' [EXPIRE_DATE]' : 'EXPIRE_DATE', ' [DTE]': 'DTE', ' [C_DELTA]' : 'C_DELTA', ' [C_GAMMA]' : 'C_GAMMA', ' [C_VEGA]': 'C_VEGA', ' [C_THETA]': 'C_THETA', ' [C_RHO]': 'C_RHO', ' [C_IV]': 'C_IV', ' [C_VOLUME]': 'C_VOLUME', ' [C_LAST]': 'C_LAST', ' [STRIKE]': 'STRIKE', ' [STRIKE_DISTANCE]': 'STRIKE_DISTANCE', ' [STRIKE_DISTANCE_PCT]': 'STRIKE_DISTANCE_PCT'}, inplace = True)

In [11]:
spy_2021.columns

Index(['[QUOTE_UNIXTIME]', 'QUOTE_READTIME', ' [QUOTE_DATE]',
       ' [QUOTE_TIME_HOURS]', 'UNDERLYING_LAST', 'EXPIRE_DATE',
       ' [EXPIRE_UNIX]', 'DTE', 'C_DELTA', 'C_GAMMA', 'C_VEGA', 'C_THETA',
       'C_RHO', 'C_IV', 'C_VOLUME', 'C_LAST', ' [C_SIZE]', ' [C_BID]',
       ' [C_ASK]', 'STRIKE', 'STRIKE_DISTANCE', 'STRIKE_DISTANCE_PCT'],
      dtype='object')

In [12]:
spy_2021.drop(columns=[ ' [QUOTE_DATE]' , ' [QUOTE_TIME_HOURS]', ' [EXPIRE_UNIX]', ' [C_SIZE]', ' [C_BID]', ' [C_ASK]'], inplace = True, axis=1)

In [13]:
spy_2021.head()

,[QUOTE_UNIXTIME],QUOTE_READTIME,UNDERLYING_LAST,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE,STRIKE_DISTANCE_PCT
0,1633095010,2021-10-01 09:30,431.04,2021-10-01,0.27,0.895780,-0.000020,0.025810,-0.030150,0.001140,7.629850,0.000000,194.650000,240.0,191.0,0.443
1,1633095010,2021-10-01 09:30,431.04,2021-10-01,0.27,1.000000,0.000000,0.000000,0.000000,0.000000,,,0.000000,245.0,186.0,0.432
2,1633095010,2021-10-01 09:30,431.04,2021-10-01,0.27,1.000000,0.000000,0.000000,0.000000,0.000000,,,0.000000,250.0,181.0,0.420
3,1633095010,2021-10-01 09:30,431.04,2021-10-01,0.27,0.902520,-0.000010,0.026350,-0.019580,0.000370,6.615720,,0.000000,255.0,176.0,0.408
4,1633095010,2021-10-01 09:30,431.04,2021-10-01,0.27,0.904220,0.000030,0.026250,-0.030310,0.000780,6.309530,1.000000,192.560000,260.0,171.0,0.397

In [14]:
spy_2021['STRIKE DISTANCE'] = spy_2021['STRIKE'] - spy_2021['UNDERLYING_LAST']

display(spy_2021.tail())

,[QUOTE_UNIXTIME],QUOTE_READTIME,UNDERLYING_LAST,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE
1518719,1640984400,2021-12-31 16:00,475.08,2024-12-20,1085.0,0.10602,0.00138,1.49641,-0.01141,1.31437,0.161220,4.000000,5.0,700.0,224.9,0.473,224.92
1518720,1640984400,2021-12-31 16:00,475.08,2024-12-20,1085.0,0.07958,0.00121,1.21556,-0.00858,1.00871,0.148750,,0.0,705.0,229.9,0.484,229.92
1518721,1640984400,2021-12-31 16:00,475.08,2024-12-20,1085.0,0.08371,0.00123,1.25581,-0.00936,1.0486,0.153330,0.000000,6.25,710.0,234.9,0.494,234.92
1518722,1640984400,2021-12-31 16:00,475.08,2024-12-20,1085.0,0.09042,0.00122,1.32934,-0.00948,1.12497,0.160460,0.000000,5.1,715.0,239.9,0.505,239.92
1518723,1640984400,2021-12-31 16:00,475.08,2024-12-20,1085.0,0.08671,0.00122,1.28974,-0.00912,1.08021,0.160750,0.000000,5.0,720.0,244.9,0.516,244.92

In [15]:
spy_2021_v2 = spy_2021.drop(columns=['STRIKE_DISTANCE'])
spy_2021_v2.head()

,[QUOTE_UNIXTIME],QUOTE_READTIME,UNDERLYING_LAST,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE
0,1633095010,2021-10-01 09:30,431.04,2021-10-01,0.27,0.895780,-0.000020,0.025810,-0.030150,0.001140,7.629850,0.000000,194.650000,240.0,0.443,-191.04
1,1633095010,2021-10-01 09:30,431.04,2021-10-01,0.27,1.000000,0.000000,0.000000,0.000000,0.000000,,,0.000000,245.0,0.432,-186.04
2,1633095010,2021-10-01 09:30,431.04,2021-10-01,0.27,1.000000,0.000000,0.000000,0.000000,0.000000,,,0.000000,250.0,0.420,-181.04
3,1633095010,2021-10-01 09:30,431.04,2021-10-01,0.27,0.902520,-0.000010,0.026350,-0.019580,0.000370,6.615720,,0.000000,255.0,0.408,-176.04
4,1633095010,2021-10-01 09:30,431.04,2021-10-01,0.27,0.904220,0.000030,0.026250,-0.030310,0.000780,6.309530,1.000000,192.560000,260.0,0.397,-171.04

In [16]:
spy_2021_v2['CONTRACT'] = spy_2021_v2['STRIKE'].astype(str) + spy_2021_v2['EXPIRE_DATE']
spy_2021_v2

,[QUOTE_UNIXTIME],QUOTE_READTIME,UNDERLYING_LAST,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE,CONTRACT
0,1633095010,2021-10-01 09:30,431.04,2021-10-01,0.27,0.895780,-0.000020,0.025810,-0.030150,0.001140,7.629850,0.000000,194.650000,240.0,0.443,-191.04,240.0 2021-10-01
1,1633095010,2021-10-01 09:30,431.04,2021-10-01,0.27,1.000000,0.000000,0.000000,0.000000,0.000000,,,0.000000,245.0,0.432,-186.04,245.0 2021-10-01
2,1633095010,2021-10-01 09:30,431.04,2021-10-01,0.27,1.000000,0.000000,0.000000,0.000000,0.000000,,,0.000000,250.0,0.420,-181.04,250.0 2021-10-01
3,1633095010,2021-10-01 09:30,431.04,2021-10-01,0.27,0.902520,-0.000010,0.026350,-0.019580,0.000370,6.615720,,0.000000,255.0,0.408,-176.04,255.0 2021-10-01
4,1633095010,2021-10-01 09:30,431.04,2021-10-01,0.27,0.904220,0.000030,0.026250,-0.030310,0.000780,6.309530,1.000000,192.560000,260.0,0.397,-171.04,260.0 2021-10-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1518719,1640984400,2021-12-31 16:00,475.08,2024-12-20,1085.00,0.10602,0.00138,1.49641,-0.01141,1.31437,0.161220,4.000000,5.0,700.0,0.473,224.92,700.0 2024-12-20
1518720,1640984400,2021-12-31 16:00,475.08,2024-12-20,1085.00,0.07958,0.00121,1.21556,-0.00858,1.00871,0.148750,,0.0,705.0,0.484,229.92,705.0 2024-12-20
1518721,1640984400,2021-12-31 16:00,475.08,2024-12-20,1085.00,0.08371,0.00123,1.25581,-0.00936,1.0486,0.153330,0.000000,6.25,710.0,0.494,234.92,710.0 2024-12-20
1518722,1640984400,2021-12-31 16:00,475.08,2024-12-20,1085.00,0.09042,0.00122,1.32934,-0.00948,1.12497,0.160460,0.000000,5.1,715.0,0.505,239.92,715.0 2024-12-20
1518723,1640984400,2021-12-31 16:00,475.08,2024-12-20,1085.00,0.08671,0.00122,1.28974,-0.00912,1.08021,0.160750,0.000000,5.0,720.0,0.516,244.92,720.0 2024-12-20

In [17]:
spy_2021_v3 = spy_2021_v2.drop(columns=['[QUOTE_UNIXTIME]'])

In [29]:
spy_2021_v4 = spy_2021_v3.loc[spy_2021_v3['DTE'] <= 5]

In [30]:
spy_2021_v4

,QUOTE_READTIME,UNDERLYING_LAST,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE,CONTRACT
0,2021-10-01 09:30,431.04,2021-10-01,0.27,0.895780,-0.000020,0.025810,-0.030150,0.001140,7.629850,0.000000,194.650000,240.0,0.443,-191.04,240.0 2021-10-01
1,2021-10-01 09:30,431.04,2021-10-01,0.27,1.000000,0.000000,0.000000,0.000000,0.000000,,,0.000000,245.0,0.432,-186.04,245.0 2021-10-01
2,2021-10-01 09:30,431.04,2021-10-01,0.27,1.000000,0.000000,0.000000,0.000000,0.000000,,,0.000000,250.0,0.420,-181.04,250.0 2021-10-01
3,2021-10-01 09:30,431.04,2021-10-01,0.27,0.902520,-0.000010,0.026350,-0.019580,0.000370,6.615720,,0.000000,255.0,0.408,-176.04,255.0 2021-10-01
4,2021-10-01 09:30,431.04,2021-10-01,0.27,0.904220,0.000030,0.026250,-0.030310,0.000780,6.309530,1.000000,192.560000,260.0,0.397,-171.04,260.0 2021-10-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1514379,2021-12-31 16:00,475.08,2022-01-05,5.00,0.00113,0.00016,0.00214,-0.00315,-0.00008,0.282750,0.000000,0.01,530.0,0.116,54.92,530.0 2022-01-05
1514380,2021-12-31 16:00,475.08,2022-01-05,5.00,0.00095,0.00017,0.00178,-0.00328,0.00002,0.326940,0.000000,0.01,540.0,0.137,64.92,540.0 2022-01-05
1514381,2021-12-31 16:00,475.08,2022-01-05,5.00,0.0009,0.00017,0.00173,-0.00355,-0.00033,0.369110,0.000000,0.02,550.0,0.158,74.92,550.0 2022-01-05
1514382,2021-12-31 16:00,475.08,2022-01-05,5.00,0.00081,0.0001,0.00138,-0.00392,0.0003,0.411060,,0.0,560.0,0.179,84.92,560.0 2022-01-05
1514383,2021-12-31 16:00,475.08,2022-01-05,5.00,0.00023,0.00005,0.00153,-0.00391,-0.00028,0.451580,0.000000,0.01,570.0,0.200,94.92,570.0 2022-01-05

In [ ]:
#spy_2021_v4 = spy2021_filtered.set_index('CONTRACT')
#spy_2021_v4

In [ ]:
#spy_2021_v2[(spy_2021_v2['STRIKE DISTANCE'] <= 15.00) & (spy_2021_v2['STRIKE DISTANCE'] > -3.00)]

In [ ]:
#spy_2021_v4['IV'] = spy_2021_v4['C_IV'] * 100 
#spy_2021_v4.tail()

In [ ]:
#

In [31]:
inception2 = spy_2021_v4[(spy_2021_v4['STRIKE DISTANCE'] <= 15.00) & (spy_2021_v4['STRIKE DISTANCE'] > -3.00)]
inception2

,QUOTE_READTIME,UNDERLYING_LAST,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE,CONTRACT
72,2021-10-01 09:30,431.04,2021-10-01,0.27,0.664760,0.078090,0.082260,-0.975070,0.007500,0.210540,5.000000,2.990000,429.0,0.005,-2.04,429.0 2021-10-01
73,2021-10-01 09:30,431.04,2021-10-01,0.27,0.591700,0.091470,0.087140,-1.179680,0.006000,0.190490,55.000000,2.230000,430.0,0.002,-1.04,430.0 2021-10-01
74,2021-10-01 09:30,431.04,2021-10-01,0.27,0.498620,0.093640,0.090030,-1.634570,0.005580,0.189480,12.000000,1.610000,431.0,0.000,-0.04,431.0 2021-10-01
75,2021-10-01 09:30,431.04,2021-10-01,0.27,0.401980,0.094180,0.087230,-1.174950,0.004200,0.182460,42.000000,1.150000,432.0,0.002,0.96,432.0 2021-10-01
76,2021-10-01 09:30,431.04,2021-10-01,0.27,0.352960,0.092350,0.083680,-0.955180,0.004500,0.178920,52.000000,0.990000,432.5,0.003,1.46,432.5 2021-10-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1514357,2021-12-31 16:00,475.08,2022-01-05,5.00,0.01884,0.00885,0.02756,-0.0177,0.00167,0.086780,606.000000,0.02,486.0,0.023,10.92,486.0 2022-01-05
1514358,2021-12-31 16:00,475.08,2022-01-05,5.00,0.01293,0.00644,0.02043,-0.01308,0.00146,0.088980,285.000000,0.04,487.0,0.025,11.92,487.0 2022-01-05
1514359,2021-12-31 16:00,475.08,2022-01-05,5.00,0.008,0.00432,0.01417,-0.0081,0.00062,0.089960,133.000000,0.02,488.0,0.027,12.92,488.0 2022-01-05
1514360,2021-12-31 16:00,475.08,2022-01-05,5.00,0.00787,0.00385,0.01317,-0.00817,0.00083,0.095090,166.000000,0.02,489.0,0.029,13.92,489.0 2022-01-05
1514361,2021-12-31 16:00,475.08,2022-01-05,5.00,0.00795,0.00348,0.0122,-0.00908,0.00086,0.101570,197.000000,0.02,490.0,0.031,14.92,490.0 2022-01-05

In [32]:
inception_filtered2 = inception2.loc[inception2['DTE'] == 4.27]
inception_filtered2

,QUOTE_READTIME,UNDERLYING_LAST,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE,CONTRACT
74888,2021-10-04 09:30,432.95,2021-10-08,4.27,0.613100,0.035560,0.193560,-0.433390,0.035380,0.212630,10.000000,5.930000,430.0,0.007,-2.95,430.0 2021-10-08
74889,2021-10-04 09:30,432.95,2021-10-08,4.27,0.579140,0.037300,0.197810,-0.431960,0.033440,0.207090,1.000000,5.210000,431.0,0.004,-1.95,431.0 2021-10-08
74890,2021-10-04 09:30,432.95,2021-10-08,4.27,0.541440,0.038580,0.201390,-0.430350,0.031570,0.202710,0.000000,5.610000,432.0,0.002,-0.95,432.0 2021-10-08
74891,2021-10-04 09:30,432.95,2021-10-08,4.27,0.502670,0.039780,0.202240,-0.423160,0.028860,0.198490,1.000000,4.010000,433.0,0.000,0.05,433.0 2021-10-08
74892,2021-10-04 09:30,432.95,2021-10-08,4.27,0.461990,0.040630,0.200810,-0.410400,0.026770,0.192610,13.000000,3.420000,434.0,0.002,1.05,434.0 2021-10-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1390327,2021-12-30 09:30,477.97,2022-01-03,4.27,0.02774,0.01246,0.03604,-0.02874,0.0021,0.092650,0.000000,0.06,488.0,0.021,10.03,488.0 2022-01-03
1390328,2021-12-30 09:30,477.97,2022-01-03,4.27,0.0222,0.00984,0.0296,-0.02454,0.00159,0.096570,0.000000,0.05,489.0,0.023,11.03,489.0 2022-01-03
1390329,2021-12-30 09:30,477.97,2022-01-03,4.27,0.01781,0.00768,0.02373,-0.01963,0.00086,0.100520,0.000000,0.04,490.0,0.025,12.03,490.0 2022-01-03
1390330,2021-12-30 09:30,477.97,2022-01-03,4.27,0.01258,0.00569,0.01807,-0.01464,0.00125,0.102180,0.000000,0.04,491.0,0.027,13.03,491.0 2022-01-03
1390331,2021-12-30 09:30,477.97,2022-01-03,4.27,0.01186,0.00506,0.01733,-0.01496,0.00051,0.108510,0.000000,0.03,492.0,0.029,14.03,492.0 2022-01-03

In [23]:
#inception_filtered3 = inception_filtered2.reset_index()

In [ ]:
#inception_filtered3

In [33]:
criteria_list2 = inception_filtered2['CONTRACT']

In [34]:
criteria_list2.count()

403

In [ ]:
#spy_2021_v5 = spy_2021_v4.reset_index()

In [35]:
spy_2021_v4.tail()

,QUOTE_READTIME,UNDERLYING_LAST,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE,CONTRACT
1514379,2021-12-31 16:00,475.08,2022-01-05,5.0,0.00113,0.00016,0.00214,-0.00315,-0.00008,0.282750,0.000000,0.01,530.0,0.116,54.92,530.0 2022-01-05
1514380,2021-12-31 16:00,475.08,2022-01-05,5.0,0.00095,0.00017,0.00178,-0.00328,0.00002,0.326940,0.000000,0.01,540.0,0.137,64.92,540.0 2022-01-05
1514381,2021-12-31 16:00,475.08,2022-01-05,5.0,0.0009,0.00017,0.00173,-0.00355,-0.00033,0.369110,0.000000,0.02,550.0,0.158,74.92,550.0 2022-01-05
1514382,2021-12-31 16:00,475.08,2022-01-05,5.0,0.00081,0.0001,0.00138,-0.00392,0.0003,0.411060,,0.0,560.0,0.179,84.92,560.0 2022-01-05
1514383,2021-12-31 16:00,475.08,2022-01-05,5.0,0.00023,0.00005,0.00153,-0.00391,-0.00028,0.451580,0.000000,0.01,570.0,0.200,94.92,570.0 2022-01-05

In [36]:
spy_2021calls = spy_2021_v4[spy_2021_v4["CONTRACT"].isin(criteria_list2)]

In [37]:
spy_2021calls.count()

QUOTE_READTIME         21236
UNDERLYING_LAST        21236
EXPIRE_DATE            21236
DTE                    21236
C_DELTA                21236
C_GAMMA                21236
C_VEGA                 21236
C_THETA                21236
C_RHO                  21236
C_IV                   21236
C_VOLUME               21236
C_LAST                 21236
STRIKE                 21236
STRIKE_DISTANCE_PCT    21236
STRIKE DISTANCE        21236
CONTRACT               21236
dtype: int64

In [38]:
spy_2021calls.iloc[4673]

QUOTE_READTIME          2021-10-18 14:30
UNDERLYING_LAST                   446.73
EXPIRE_DATE                   2021-10-22
DTE                                 4.06
C_DELTA                         0.022600
C_GAMMA                         0.010200
C_VEGA                          0.027860
C_THETA                        -0.024890
C_RHO                           0.001160
C_IV                            0.103470
C_VOLUME                       34.000000
C_LAST                          0.040000
STRIKE                             457.5
STRIKE_DISTANCE_PCT                0.024
STRIKE DISTANCE                    10.77
CONTRACT                457.5 2021-10-22
Name: 858580, dtype: object

In [39]:
spy_2021calls['C_IV'] = pd.to_numeric(spy_2021calls['C_IV'], errors = 'coerce')
spy_2021calls['C_LAST'] = pd.to_numeric(spy_2021calls['C_LAST'], errors = 'coerce')
spy_2021calls['C_VOLUME'] = pd.to_numeric(spy_2021calls['C_VOLUME'], errors = 'coerce')

C:\Users\aarch\AppData\Local\Temp\ipykernel_5980\2775156084.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  spy_2021calls['C_IV'] = pd.to_numeric(spy_2021calls['C_IV'], errors = 'coerce')
C:\Users\aarch\AppData\Local\Temp\ipykernel_5980\2775156084.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  spy_2021calls['C_LAST'] = pd.to_numeric(spy_2021calls['C_LAST'], errors = 'coerce')
C:\Users\aarch\AppData\Local\Temp\ipykernel_5980\2775156084.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  spy_2021calls['C_VOLUME'] = pd.to_numeric(spy_2021calls['C_VOLUME'], errors = 'coerce')

In [40]:
spy_2021calls

,QUOTE_READTIME,UNDERLYING_LAST,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE,CONTRACT
74888,2021-10-04 09:30,432.95,2021-10-08,4.27,0.613100,0.035560,0.193560,-0.433390,0.035380,0.21263,10.0,5.93,430.0,0.007,-2.95,430.0 2021-10-08
74889,2021-10-04 09:30,432.95,2021-10-08,4.27,0.579140,0.037300,0.197810,-0.431960,0.033440,0.20709,1.0,5.21,431.0,0.004,-1.95,431.0 2021-10-08
74890,2021-10-04 09:30,432.95,2021-10-08,4.27,0.541440,0.038580,0.201390,-0.430350,0.031570,0.20271,0.0,5.61,432.0,0.002,-0.95,432.0 2021-10-08
74891,2021-10-04 09:30,432.95,2021-10-08,4.27,0.502670,0.039780,0.202240,-0.423160,0.028860,0.19849,1.0,4.01,433.0,0.000,0.05,433.0 2021-10-08
74892,2021-10-04 09:30,432.95,2021-10-08,4.27,0.461990,0.040630,0.200810,-0.410400,0.026770,0.19261,13.0,3.42,434.0,0.002,1.05,434.0 2021-10-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1514249,2021-12-31 16:00,475.08,2022-01-03,3.00,0.00302,0.0022,0.00518,-0.00389,-0.00019,0.09822,78.0,0.01,488.0,0.027,12.92,488.0 2022-01-03
1514250,2021-12-31 16:00,475.08,2022-01-03,3.00,0.0029,0.00195,0.00497,-0.00431,0.00062,0.10536,14.0,0.01,489.0,0.029,13.92,489.0 2022-01-03
1514251,2021-12-31 16:00,475.08,2022-01-03,3.00,0.00322,0.00181,0.00489,-0.00442,-0.00013,0.11144,10.0,0.01,490.0,0.031,14.92,490.0 2022-01-03
1514252,2021-12-31 16:00,475.08,2022-01-03,3.00,0.00283,0.0016,0.00402,-0.00455,0.00025,0.11820,50.0,0.01,491.0,0.034,15.92,491.0 2022-01-03
1514253,2021-12-31 16:00,475.08,2022-01-03,3.00,0.00247,0.00139,0.00425,-0.00382,0.00025,0.12516,3.0,0.01,492.0,0.036,16.92,492.0 2022-01-03

In [41]:
spy_2021calls.to_csv("spy_2021callsv1.csv", index=None)