In [ ]:
import pandas as pd 
import numpy as np 
from pathlib import Path

In [ ]:
spy_oct = pd.read_csv("spy_30x_202110.txt")
#spy_oct.to_csv("spy_30x_202110.csv", index=None)

In [ ]:
spy_nov = pd.read_csv("spy_30x_202111.txt")
#spy_nov.to_csv("spy_30x_202111.csv", index=None)

In [ ]:
spy_dec = pd.read_csv("spy_30x_202112.txt")
#spy_dec.to_csv("spy_30x_202112.csv", index=None)

In [ ]:
spy_2021 = pd.concat([spy_oct, spy_nov, spy_dec], axis=0)

In [ ]:
spy_2021.columns

In [ ]:
#spy_add = spy_2021.loc[' [STRIKE_DISTANCE]']

In [ ]:
spy_2021.drop(columns = [' [P_BID]',' [P_ASK]', ' [P_SIZE]', ' [P_LAST]', ' [P_DELTA]', ' [P_GAMMA]',' [P_VEGA]', ' [P_THETA]', ' [P_RHO]', ' [P_IV]', ' [P_VOLUME]'], inplace = True, axis=1)

In [ ]:
spy_2021.head()

In [ ]:
spy_2021.rename(columns = {' [QUOTE_READTIME]': 'QUOTE_READTIME',' [UNDERLYING_LAST]': 'UNDERLYING_LAST', ' [EXPIRE_DATE]' : 'EXPIRE_DATE', ' [DTE]': 'DTE', ' [C_DELTA]' : 'C_DELTA', ' [C_GAMMA]' : 'C_GAMMA', ' [C_VEGA]': 'C_VEGA', ' [C_THETA]': 'C_THETA', ' [C_RHO]': 'C_RHO', ' [C_IV]': 'C_IV', ' [C_VOLUME]': 'C_VOLUME', ' [C_LAST]': 'C_LAST', ' [STRIKE]': 'STRIKE', ' [STRIKE_DISTANCE]': 'STRIKE_DISTANCE', ' [STRIKE_DISTANCE_PCT]': 'STRIKE_DISTANCE_PCT'}, inplace = True)

In [ ]:
spy_2021.columns

In [ ]:
spy_2021.drop(columns=[ ' [QUOTE_DATE]' , ' [QUOTE_TIME_HOURS]', ' [EXPIRE_UNIX]', ' [C_SIZE]', ' [C_BID]', ' [C_ASK]'], inplace = True, axis=1)

In [ ]:
spy_2021.head()

In [ ]:
spy_2021['STRIKE DISTANCE'] = spy_2021['STRIKE'] - spy_2021['UNDERLYING_LAST']

display(spy_2021.tail())

In [ ]:
spy_2021_v2 = spy_2021.drop(columns=['STRIKE_DISTANCE'])
spy_2021_v2.head()

In [ ]:
spy_2021_v2['CONTRACT'] = spy_2021_v2['STRIKE'].astype(str) + spy_2021_v2['EXPIRE_DATE']
spy_2021_v2

In [ ]:
spy_2021_v3 = spy_2021_v2.drop(columns=['[QUOTE_UNIXTIME]'])

In [ ]:
spy_2021_v4 = spy_2021_v3.loc[spy_2021_v3['DTE'] <= 5]

In [ ]:
spy_2021_v4

In [ ]:
#spy_2021_v4 = spy2021_filtered.set_index('CONTRACT')
#spy_2021_v4

In [ ]:
#spy_2021_v2[(spy_2021_v2['STRIKE DISTANCE'] <= 15.00) & (spy_2021_v2['STRIKE DISTANCE'] > -3.00)]

In [ ]:
#spy_2021_v4['IV'] = spy_2021_v4['C_IV'] * 100 
#spy_2021_v4.tail()

In [ ]:
#

In [ ]:
inception2 = spy_2021_v4[(spy_2021_v4['STRIKE DISTANCE'] <= 15.00) & (spy_2021_v4['STRIKE DISTANCE'] > -3.00)]
inception2

In [ ]:
inception_filtered2 = inception2.loc[inception2['DTE'] == 4.27]
inception_filtered2

In [ ]:
#inception_filtered3 = inception_filtered2.reset_index()

In [ ]:
#inception_filtered3

In [ ]:
criteria_list2 = inception_filtered2['CONTRACT']

In [ ]:
criteria_list2.count()

In [ ]:
#spy_2021_v5 = spy_2021_v4.reset_index()

In [ ]:
spy_2021_v4.tail()

In [ ]:
spy_2021calls = spy_2021_v4[spy_2021_v4["CONTRACT"].isin(criteria_list2)]

In [ ]:
spy_2021calls.count()

In [ ]:
spy_2021calls.iloc[4673]

In [ ]:
spy_2021calls['C_IV'] = pd.to_numeric(spy_2021calls['C_IV'], errors = 'coerce')
spy_2021calls['C_LAST'] = pd.to_numeric(spy_2021calls['C_LAST'], errors = 'coerce')
spy_2021calls['C_VOLUME'] = pd.to_numeric(spy_2021calls['C_VOLUME'], errors = 'coerce')

In [ ]:
spy_2021calls

In [ ]:
spy_2021calls.to_csv("spy_2021callsv1.csv", index=None)

# __START HERE to calculate 'y' and filter DTE__

In [1]:
import pandas as pd 
import numpy as np 
from pathlib import Path

In [2]:
spy_path = Path('spy_2021callsv1.csv')
spy_21_q4 = pd.read_csv(spy_path)

In [3]:
spy_21_q4 = spy_21_q4.set_index('CONTRACT')

In [4]:
spy_21_q4["PRICECLOSE"] = spy_21_q4.loc[spy_21_q4['DTE'] == 2.0, 'C_LAST']
spy_21_q4.head()

,QUOTE_READTIME,UNDERLYING_LAST,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE,PRICECLOSE
CONTRACT,,,,,,,,,,,,,,,,
430.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.61310,0.03556,0.19356,-0.43339,0.03538,0.21263,10.0,5.93,430.0,0.007,-2.95,6.11
431.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.57914,0.03730,0.19781,-0.43196,0.03344,0.20709,1.0,5.21,431.0,0.004,-1.95,5.31
432.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.54144,0.03858,0.20139,-0.43035,0.03157,0.20271,0.0,5.61,432.0,0.002,-0.95,4.63
433.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.50267,0.03978,0.20224,-0.42316,0.02886,0.19849,1.0,4.01,433.0,0.000,0.05,3.95
434.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.46199,0.04063,0.20081,-0.41040,0.02677,0.19261,13.0,3.42,434.0,0.002,1.05,3.22

In [5]:
spy_21_q4['ROI3'] = spy_21_q4["PRICECLOSE"] / spy_21_q4['C_LAST']
spy_21_q4.head()

,QUOTE_READTIME,UNDERLYING_LAST,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE,PRICECLOSE,ROI3
CONTRACT,,,,,,,,,,,,,,,,,
430.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.61310,0.03556,0.19356,-0.43339,0.03538,0.21263,10.0,5.93,430.0,0.007,-2.95,6.11,1.030354
431.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.57914,0.03730,0.19781,-0.43196,0.03344,0.20709,1.0,5.21,431.0,0.004,-1.95,5.31,1.019194
432.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.54144,0.03858,0.20139,-0.43035,0.03157,0.20271,0.0,5.61,432.0,0.002,-0.95,4.63,0.825312
433.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.50267,0.03978,0.20224,-0.42316,0.02886,0.19849,1.0,4.01,433.0,0.000,0.05,3.95,0.985037
434.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.46199,0.04063,0.20081,-0.41040,0.02677,0.19261,13.0,3.42,434.0,0.002,1.05,3.22,0.941520

In [6]:
spy_21_q4['ROI %'] = (spy_21_q4['ROI3'] - 1) * 100
spy_21_q4.head(100)

,QUOTE_READTIME,UNDERLYING_LAST,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE,PRICECLOSE,ROI3,ROI %
CONTRACT,,,,,,,,,,,,,,,,,,
430.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.61310,0.03556,0.19356,-0.43339,0.03538,0.21263,10.0,5.93,430.0,0.007,-2.95,6.11,1.030354,3.035413
431.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.57914,0.03730,0.19781,-0.43196,0.03344,0.20709,1.0,5.21,431.0,0.004,-1.95,5.31,1.019194,1.919386
432.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.54144,0.03858,0.20139,-0.43035,0.03157,0.20271,0.0,5.61,432.0,0.002,-0.95,4.63,0.825312,-17.468806
433.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.50267,0.03978,0.20224,-0.42316,0.02886,0.19849,1.0,4.01,433.0,0.000,0.05,3.95,0.985037,-1.496259
434.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.46199,0.04063,0.20081,-0.41040,0.02677,0.19261,13.0,3.42,434.0,0.002,1.05,3.22,0.941520,-5.847953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440.0 2021-10-08,2021-10-04 11:30,427.84,2021-10-08,4.19,0.09459,0.01857,0.08358,-0.14730,0.00528,0.18216,3273.0,0.39,440.0,0.028,12.16,0.64,1.641026,64.102564
441.0 2021-10-08,2021-10-04 11:30,427.84,2021-10-08,4.19,0.07627,0.01590,0.07131,-0.12248,0.00468,0.18092,3524.0,0.31,441.0,0.031,13.16,0.45,1.451613,45.161290
442.0 2021-10-08,2021-10-04 11:30,427.84,2021-10-08,4.19,0.06135,0.01351,0.06036,-0.10131,0.00391,0.18018,2276.0,0.25,442.0,0.033,14.16,0.32,1.280000,28.000000
442.5 2021-10-08,2021-10-04 11:30,427.84,2021-10-08,4.19,0.05586,0.01254,0.05671,-0.09521,0.00315,0.18215,1101.0,0.23,442.5,0.034,14.66,0.27,1.173913,17.391304
443.0 2021-10-08,2021-10-04 11:30,427.84,2021-10-08,4.19,0.04961,0.01144,0.05062,-0.08451,0.00261,0.18140,2959.0,0.20,443.0,0.035,15.16,0.22,1.100000,10.000000

In [7]:
spy_21_q4 = spy_21_q4.drop(columns=['ROI3'])
spy_21_q4.head()

,QUOTE_READTIME,UNDERLYING_LAST,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE,PRICECLOSE,ROI %
CONTRACT,,,,,,,,,,,,,,,,,
430.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.61310,0.03556,0.19356,-0.43339,0.03538,0.21263,10.0,5.93,430.0,0.007,-2.95,6.11,3.035413
431.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.57914,0.03730,0.19781,-0.43196,0.03344,0.20709,1.0,5.21,431.0,0.004,-1.95,5.31,1.919386
432.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.54144,0.03858,0.20139,-0.43035,0.03157,0.20271,0.0,5.61,432.0,0.002,-0.95,4.63,-17.468806
433.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.50267,0.03978,0.20224,-0.42316,0.02886,0.19849,1.0,4.01,433.0,0.000,0.05,3.95,-1.496259
434.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.46199,0.04063,0.20081,-0.41040,0.02677,0.19261,13.0,3.42,434.0,0.002,1.05,3.22,-5.847953

In [8]:
#APPROACH A: 6 categories

#spy_21_q4.loc[spy_21_q4["ROI %"] <= -60, "y"] = 0
#spy_21_q4.loc[(spy_21_q4["ROI %"] <= -10) & (spy_21_q4["ROI %"] > -60), "y"] = 1
#spy_21_q4.loc[(spy_21_q4["ROI %"] <= 10) & (spy_21_q4["ROI %"] > -10), "y"] = 2
#spy_21_q4.loc[(spy_21_q4["ROI %"] <= 60) & (spy_21_q4["ROI %"] > 10), "y"] = 3
#spy_21_q4.loc[(spy_21_q4["ROI %"] > 60) & (spy_21_q4["ROI %"] < 100), "y"] = 4
#spy_21_q4.loc[spy_21_q4["ROI %"] >= 100, "y"] = 5

In [10]:
#APPROACH B: 3 categories 

spy_21_q4.loc[spy_21_q4["ROI %"] <= -30, "y"] = 0

spy_21_q4.loc[(spy_21_q4["ROI %"] <= 25) & (spy_21_q4["ROI %"] > -30), "y"] = 1

spy_21_q4.loc[spy_21_q4["ROI %"] > 25, "y"] = 2

In [11]:
spy_21_q4["y"].value_counts()

2.0    4981
0.0    4709
1.0    4676
Name: y, dtype: int64

In [12]:
spy_21_q4.rename(columns = {'UNDERLYING_LAST': 'SPY PRICE'}, inplace = True)
spy_21_q4.head()

,QUOTE_READTIME,SPY PRICE,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE,PRICECLOSE,ROI %,y
CONTRACT,,,,,,,,,,,,,,,,,,
430.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.61310,0.03556,0.19356,-0.43339,0.03538,0.21263,10.0,5.93,430.0,0.007,-2.95,6.11,3.035413,1.0
431.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.57914,0.03730,0.19781,-0.43196,0.03344,0.20709,1.0,5.21,431.0,0.004,-1.95,5.31,1.919386,1.0
432.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.54144,0.03858,0.20139,-0.43035,0.03157,0.20271,0.0,5.61,432.0,0.002,-0.95,4.63,-17.468806,1.0
433.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.50267,0.03978,0.20224,-0.42316,0.02886,0.19849,1.0,4.01,433.0,0.000,0.05,3.95,-1.496259,1.0
434.0 2021-10-08,2021-10-04 09:30,432.95,2021-10-08,4.27,0.46199,0.04063,0.20081,-0.41040,0.02677,0.19261,13.0,3.42,434.0,0.002,1.05,3.22,-5.847953,1.0

In [13]:
spy_21_q4.reset_index(inplace=True)

In [14]:
spy_21_q4 = spy_21_q4.set_index('QUOTE_READTIME')
spy_21_q4.head()

,CONTRACT,SPY PRICE,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE,PRICECLOSE,ROI %,y
QUOTE_READTIME,,,,,,,,,,,,,,,,,,
2021-10-04 09:30,430.0 2021-10-08,432.95,2021-10-08,4.27,0.61310,0.03556,0.19356,-0.43339,0.03538,0.21263,10.0,5.93,430.0,0.007,-2.95,6.11,3.035413,1.0
2021-10-04 09:30,431.0 2021-10-08,432.95,2021-10-08,4.27,0.57914,0.03730,0.19781,-0.43196,0.03344,0.20709,1.0,5.21,431.0,0.004,-1.95,5.31,1.919386,1.0
2021-10-04 09:30,432.0 2021-10-08,432.95,2021-10-08,4.27,0.54144,0.03858,0.20139,-0.43035,0.03157,0.20271,0.0,5.61,432.0,0.002,-0.95,4.63,-17.468806,1.0
2021-10-04 09:30,433.0 2021-10-08,432.95,2021-10-08,4.27,0.50267,0.03978,0.20224,-0.42316,0.02886,0.19849,1.0,4.01,433.0,0.000,0.05,3.95,-1.496259,1.0
2021-10-04 09:30,434.0 2021-10-08,432.95,2021-10-08,4.27,0.46199,0.04063,0.20081,-0.41040,0.02677,0.19261,13.0,3.42,434.0,0.002,1.05,3.22,-5.847953,1.0

In [15]:
spy_21_q4.index = pd.to_datetime(spy_21_q4.index, infer_datetime_format=True)
spy_21_q4.head()

,CONTRACT,SPY PRICE,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE,PRICECLOSE,ROI %,y
QUOTE_READTIME,,,,,,,,,,,,,,,,,,
2021-10-04 09:30:00,430.0 2021-10-08,432.95,2021-10-08,4.27,0.61310,0.03556,0.19356,-0.43339,0.03538,0.21263,10.0,5.93,430.0,0.007,-2.95,6.11,3.035413,1.0
2021-10-04 09:30:00,431.0 2021-10-08,432.95,2021-10-08,4.27,0.57914,0.03730,0.19781,-0.43196,0.03344,0.20709,1.0,5.21,431.0,0.004,-1.95,5.31,1.919386,1.0
2021-10-04 09:30:00,432.0 2021-10-08,432.95,2021-10-08,4.27,0.54144,0.03858,0.20139,-0.43035,0.03157,0.20271,0.0,5.61,432.0,0.002,-0.95,4.63,-17.468806,1.0
2021-10-04 09:30:00,433.0 2021-10-08,432.95,2021-10-08,4.27,0.50267,0.03978,0.20224,-0.42316,0.02886,0.19849,1.0,4.01,433.0,0.000,0.05,3.95,-1.496259,1.0
2021-10-04 09:30:00,434.0 2021-10-08,432.95,2021-10-08,4.27,0.46199,0.04063,0.20081,-0.41040,0.02677,0.19261,13.0,3.42,434.0,0.002,1.05,3.22,-5.847953,1.0

In [16]:
#Drops all rows after DTE2.0

spy_21_q4_filt = spy_21_q4.loc[(spy_21_q4["DTE"]<=4.27) & (spy_21_q4["DTE"]>=2.0)]

In [17]:
spy_21_q4_filt.shape

(13602, 18)

In [18]:
spy_21_q4_filt = spy_21_q4_filt.dropna()

In [19]:
spy_21_q4_filt.shape

(9047, 18)

In [20]:
spy_21_q4_filt.to_csv("./Resources/spy_21_q4_filt.csv", index=True)

# __START HERE to concat with Q1 2022 (missing inflation, VIX, Sentiment)__

In [21]:
import pandas as pd 
import numpy as np 
from pathlib import Path

In [22]:
#Importing 2022 Q1 (version that does NOT include VIX and Sentiment)

spy_path = Path('./Resources/spy_22_q1_filt.csv')
spy_22_q1_filt = pd.read_csv(spy_path)

In [23]:
spy_22_q1_filt.set_index(["QUOTE_READTIME"], inplace=True)

In [24]:
spy_22_q1_filt.head()

,CONTRACT,SPY PRICE,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE,INFLATION%,PRICECLOSE,ROI %,y
QUOTE_READTIME,,,,,,,,,,,,,,,,,,,
2022-01-03 09:30:00,474.0 2022-01-07,476.43,1/7/2022,4.27,0.62598,0.05055,0.21136,-0.28773,0.03788,0.13515,1,4.26,474,0.005,-2.43,0.8,0.55,-87.089202,0.0
2022-01-03 09:30:00,475.0 2022-01-07,476.43,1/7/2022,4.27,0.57735,0.05466,0.21805,-0.28592,0.03511,0.12942,32,3.62,475,0.003,-1.43,0.8,0.39,-89.226519,0.0
2022-01-03 09:30:00,476.0 2022-01-07,476.43,1/7/2022,4.27,0.52223,0.05633,0.22191,-0.28818,0.03208,0.12704,22,3.04,476,0.001,-0.43,0.8,0.29,-90.460526,0.0
2022-01-03 09:30:00,477.0 2022-01-07,476.43,1/7/2022,4.27,0.46442,0.05760,0.22168,-0.28057,0.02945,0.12402,161,2.46,477,0.001,0.57,0.8,0.21,-91.463415,0.0
2022-01-03 09:30:00,478.0 2022-01-07,476.43,1/7/2022,4.27,0.40460,0.05815,0.21613,-0.26381,0.02541,0.11971,0,1.51,478,0.003,1.57,0.8,0.15,-90.066225,0.0

In [25]:
spy_22_q1_filt.shape

(9239, 19)

In [26]:
spy_22_q1_filt.drop(columns=["INFLATION%"], inplace=True)

In [27]:
q4_21_q1_22 = pd.concat([spy_21_q4_filt, spy_22_q1_filt])

In [28]:
q4_21_q1_22

,CONTRACT,SPY PRICE,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE,PRICECLOSE,ROI %,y
QUOTE_READTIME,,,,,,,,,,,,,,,,,,
2021-10-04 09:30:00,430.0 2021-10-08,432.95,2021-10-08,4.27,0.61310,0.03556,0.19356,-0.43339,0.03538,0.21263,10.0,5.93,430.0,0.007,-2.95,6.11,3.035413,1.0
2021-10-04 09:30:00,431.0 2021-10-08,432.95,2021-10-08,4.27,0.57914,0.03730,0.19781,-0.43196,0.03344,0.20709,1.0,5.21,431.0,0.004,-1.95,5.31,1.919386,1.0
2021-10-04 09:30:00,432.0 2021-10-08,432.95,2021-10-08,4.27,0.54144,0.03858,0.20139,-0.43035,0.03157,0.20271,0.0,5.61,432.0,0.002,-0.95,4.63,-17.468806,1.0
2021-10-04 09:30:00,433.0 2021-10-08,432.95,2021-10-08,4.27,0.50267,0.03978,0.20224,-0.42316,0.02886,0.19849,1.0,4.01,433.0,0.000,0.05,3.95,-1.496259,1.0
2021-10-04 09:30:00,434.0 2021-10-08,432.95,2021-10-08,4.27,0.46199,0.04063,0.20081,-0.41040,0.02677,0.19261,13.0,3.42,434.0,0.002,1.05,3.22,-5.847953,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-03-23 16:00:00,455.0 2022-03-25,443.84,3/25/2022,2.00,0.04696,0.01493,0.03746,-0.09216,0.00106,0.17010,12879.0,0.13,455.0,0.025,11.16,0.13,0.000000,1.0
2022-03-23 16:00:00,456.0 2022-03-25,443.84,3/25/2022,2.00,0.03309,0.01144,0.02826,-0.06611,0.00075,0.16963,10707.0,0.09,456.0,0.027,12.16,0.09,0.000000,1.0
2022-03-23 16:00:00,457.0 2022-03-25,443.84,3/25/2022,2.00,0.02264,0.00839,0.02085,-0.04539,0.00083,0.16879,4434.0,0.05,457.0,0.030,13.16,0.05,0.000000,1.0
2022-03-23 16:00:00,458.0 2022-03-25,443.84,3/25/2022,2.00,0.01819,0.00688,0.01736,-0.03784,0.00030,0.17380,4001.0,0.04,458.0,0.032,14.16,0.04,0.000000,1.0
2022-03-23 16:00:00,459.0 2022-03-25,443.84,3/25/2022,2.00,0.01514,0.00542,0.01463,-0.03065,0.00091,0.17742,2672.0,0.03,459.0,0.034,15.16,0.03,0.000000,1.0

In [29]:
q4_21_q1_22 = q4_21_q1_22.dropna()

In [30]:
q4_21_q1_22

,CONTRACT,SPY PRICE,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE,PRICECLOSE,ROI %,y
QUOTE_READTIME,,,,,,,,,,,,,,,,,,
2021-10-04 09:30:00,430.0 2021-10-08,432.95,2021-10-08,4.27,0.61310,0.03556,0.19356,-0.43339,0.03538,0.21263,10.0,5.93,430.0,0.007,-2.95,6.11,3.035413,1.0
2021-10-04 09:30:00,431.0 2021-10-08,432.95,2021-10-08,4.27,0.57914,0.03730,0.19781,-0.43196,0.03344,0.20709,1.0,5.21,431.0,0.004,-1.95,5.31,1.919386,1.0
2021-10-04 09:30:00,432.0 2021-10-08,432.95,2021-10-08,4.27,0.54144,0.03858,0.20139,-0.43035,0.03157,0.20271,0.0,5.61,432.0,0.002,-0.95,4.63,-17.468806,1.0
2021-10-04 09:30:00,433.0 2021-10-08,432.95,2021-10-08,4.27,0.50267,0.03978,0.20224,-0.42316,0.02886,0.19849,1.0,4.01,433.0,0.000,0.05,3.95,-1.496259,1.0
2021-10-04 09:30:00,434.0 2021-10-08,432.95,2021-10-08,4.27,0.46199,0.04063,0.20081,-0.41040,0.02677,0.19261,13.0,3.42,434.0,0.002,1.05,3.22,-5.847953,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-03-23 16:00:00,455.0 2022-03-25,443.84,3/25/2022,2.00,0.04696,0.01493,0.03746,-0.09216,0.00106,0.17010,12879.0,0.13,455.0,0.025,11.16,0.13,0.000000,1.0
2022-03-23 16:00:00,456.0 2022-03-25,443.84,3/25/2022,2.00,0.03309,0.01144,0.02826,-0.06611,0.00075,0.16963,10707.0,0.09,456.0,0.027,12.16,0.09,0.000000,1.0
2022-03-23 16:00:00,457.0 2022-03-25,443.84,3/25/2022,2.00,0.02264,0.00839,0.02085,-0.04539,0.00083,0.16879,4434.0,0.05,457.0,0.030,13.16,0.05,0.000000,1.0
2022-03-23 16:00:00,458.0 2022-03-25,443.84,3/25/2022,2.00,0.01819,0.00688,0.01736,-0.03784,0.00030,0.17380,4001.0,0.04,458.0,0.032,14.16,0.04,0.000000,1.0
2022-03-23 16:00:00,459.0 2022-03-25,443.84,3/25/2022,2.00,0.01514,0.00542,0.01463,-0.03065,0.00091,0.17742,2672.0,0.03,459.0,0.034,15.16,0.03,0.000000,1.0

In [31]:
q4_21_q1_22.shape

(18286, 18)

In [33]:
q4_21_q1_22.to_csv("./Resources/q4_21_q1_22.csv", index=True)


# __START HERE 07/06 11:00PM to select certain ranges of train/test data instead of random train/test/split__

In [34]:
import pandas as pd 
import numpy as np 
from pathlib import Path

In [35]:
spy_path = Path('./Resources/q4_21_q1_22.csv')
df = pd.read_csv(spy_path)
df

,QUOTE_READTIME,CONTRACT,SPY PRICE,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE,PRICECLOSE,ROI %,y
0,2021-10-04 09:30:00,430.0 2021-10-08,432.95,2021-10-08,4.27,0.61310,0.03556,0.19356,-0.43339,0.03538,0.21263,10.0,5.93,430.0,0.007,-2.95,6.11,3.035413,1.0
1,2021-10-04 09:30:00,431.0 2021-10-08,432.95,2021-10-08,4.27,0.57914,0.03730,0.19781,-0.43196,0.03344,0.20709,1.0,5.21,431.0,0.004,-1.95,5.31,1.919386,1.0
2,2021-10-04 09:30:00,432.0 2021-10-08,432.95,2021-10-08,4.27,0.54144,0.03858,0.20139,-0.43035,0.03157,0.20271,0.0,5.61,432.0,0.002,-0.95,4.63,-17.468806,1.0
3,2021-10-04 09:30:00,433.0 2021-10-08,432.95,2021-10-08,4.27,0.50267,0.03978,0.20224,-0.42316,0.02886,0.19849,1.0,4.01,433.0,0.000,0.05,3.95,-1.496259,1.0
4,2021-10-04 09:30:00,434.0 2021-10-08,432.95,2021-10-08,4.27,0.46199,0.04063,0.20081,-0.41040,0.02677,0.19261,13.0,3.42,434.0,0.002,1.05,3.22,-5.847953,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18281,2022-03-23 16:00:00,455.0 2022-03-25,443.84,3/25/2022,2.00,0.04696,0.01493,0.03746,-0.09216,0.00106,0.17010,12879.0,0.13,455.0,0.025,11.16,0.13,0.000000,1.0
18282,2022-03-23 16:00:00,456.0 2022-03-25,443.84,3/25/2022,2.00,0.03309,0.01144,0.02826,-0.06611,0.00075,0.16963,10707.0,0.09,456.0,0.027,12.16,0.09,0.000000,1.0
18283,2022-03-23 16:00:00,457.0 2022-03-25,443.84,3/25/2022,2.00,0.02264,0.00839,0.02085,-0.04539,0.00083,0.16879,4434.0,0.05,457.0,0.030,13.16,0.05,0.000000,1.0
18284,2022-03-23 16:00:00,458.0 2022-03-25,443.84,3/25/2022,2.00,0.01819,0.00688,0.01736,-0.03784,0.00030,0.17380,4001.0,0.04,458.0,0.032,14.16,0.04,0.000000,1.0
18285,2022-03-23 16:00:00,459.0 2022-03-25,443.84,3/25/2022,2.00,0.01514,0.00542,0.01463,-0.03065,0.00091,0.17742,2672.0,0.03,459.0,0.034,15.16,0.03,0.000000,1.0

In [36]:
df.shape

(18286, 19)

In [37]:
test_2qs = df.iloc[4300:7957]
test_2qs

,QUOTE_READTIME,CONTRACT,SPY PRICE,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE,PRICECLOSE,ROI %,y
4300,2021-11-10 15:30:00,479.0 2021-11-12,463.84,2021-11-12,2.02,0.00700,0.00341,0.00871,-0.01352,0.00064,0.15175,146.0,0.02,479.0,0.033,15.16,0.02,0.000000,1.0
4301,2021-11-10 15:30:00,480.0 2021-11-12,463.84,2021-11-12,2.02,0.00293,0.00153,0.00347,-0.00459,0.00024,0.14230,1420.0,0.01,480.0,0.035,16.16,0.01,0.000000,1.0
4302,2021-11-10 15:30:00,481.0 2021-11-12,463.84,2021-11-12,2.02,0.00295,0.00137,0.00316,-0.00423,0.00015,0.15095,1778.0,0.01,481.0,0.037,17.16,0.01,0.000000,1.0
4303,2021-11-10 15:30:00,482.0 2021-11-12,463.84,2021-11-12,2.02,0.00264,0.00126,0.00349,-0.00437,0.00030,0.15848,2.0,0.01,482.0,0.039,18.16,0.01,0.000000,1.0
4304,2021-11-10 15:30:00,483.0 2021-11-12,463.84,2021-11-12,2.02,0.00241,0.00114,0.00308,-0.00497,-0.00041,0.16543,537.0,0.01,483.0,0.041,19.16,0.01,0.000000,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7952,2021-12-14 14:00:00,471.0 2021-12-17,460.67,2021-12-17,3.08,0.08263,0.01815,0.07200,-0.13194,0.00401,0.18033,3500.0,0.32,471.0,0.022,10.33,1.69,428.125000,2.0
7953,2021-12-14 14:00:00,472.0 2021-12-17,460.67,2021-12-17,3.08,0.06546,0.01533,0.06078,-0.10882,0.00307,0.17901,3794.0,0.24,472.0,0.025,11.33,1.25,420.833333,2.0
7954,2021-12-14 14:00:00,473.0 2021-12-17,460.67,2021-12-17,3.08,0.05229,0.01277,0.05087,-0.09034,0.00195,0.17969,2079.0,0.18,473.0,0.027,12.33,0.90,400.000000,2.0
7955,2021-12-14 14:00:00,474.0 2021-12-17,460.67,2021-12-17,3.08,0.04256,0.01065,0.04231,-0.07467,0.00214,0.18106,2847.0,0.15,474.0,0.029,13.33,0.62,313.333333,2.0
7956,2021-12-14 14:00:00,475.0 2021-12-17,460.67,2021-12-17,3.08,0.03183,0.00849,0.03370,-0.05831,0.00150,0.17942,26137.0,0.11,475.0,0.031,14.33,0.41,272.727273,2.0

In [38]:
train1 = df.iloc[:4299]
train1

,QUOTE_READTIME,CONTRACT,SPY PRICE,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE,PRICECLOSE,ROI %,y
0,2021-10-04 09:30:00,430.0 2021-10-08,432.95,2021-10-08,4.27,0.61310,0.03556,0.19356,-0.43339,0.03538,0.21263,10.0,5.93,430.0,0.007,-2.95,6.11,3.035413,1.0
1,2021-10-04 09:30:00,431.0 2021-10-08,432.95,2021-10-08,4.27,0.57914,0.03730,0.19781,-0.43196,0.03344,0.20709,1.0,5.21,431.0,0.004,-1.95,5.31,1.919386,1.0
2,2021-10-04 09:30:00,432.0 2021-10-08,432.95,2021-10-08,4.27,0.54144,0.03858,0.20139,-0.43035,0.03157,0.20271,0.0,5.61,432.0,0.002,-0.95,4.63,-17.468806,1.0
3,2021-10-04 09:30:00,433.0 2021-10-08,432.95,2021-10-08,4.27,0.50267,0.03978,0.20224,-0.42316,0.02886,0.19849,1.0,4.01,433.0,0.000,0.05,3.95,-1.496259,1.0
4,2021-10-04 09:30:00,434.0 2021-10-08,432.95,2021-10-08,4.27,0.46199,0.04063,0.20081,-0.41040,0.02677,0.19261,13.0,3.42,434.0,0.002,1.05,3.22,-5.847953,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4294,2021-11-10 15:30:00,473.0 2021-11-12,463.84,2021-11-12,2.02,0.02544,0.01283,0.02425,-0.03576,0.00112,0.11570,7603.0,0.05,473.0,0.020,9.16,0.05,0.000000,1.0
4295,2021-11-10 15:30:00,474.0 2021-11-12,463.84,2021-11-12,2.02,0.01956,0.00987,0.01877,-0.02865,0.00105,0.12076,4049.0,0.04,474.0,0.022,10.16,0.03,-25.000000,1.0
4296,2021-11-10 15:30:00,475.0 2021-11-12,463.84,2021-11-12,2.02,0.01408,0.00725,0.01465,-0.02187,0.00064,0.12456,9148.0,0.03,475.0,0.024,11.16,0.03,0.000000,1.0
4297,2021-11-10 15:30:00,476.0 2021-11-12,463.84,2021-11-12,2.02,0.01311,0.00628,0.01317,-0.02190,0.00052,0.13372,1060.0,0.03,476.0,0.026,12.16,0.01,-66.666667,0.0
4298,2021-11-10 15:30:00,477.0 2021-11-12,463.84,2021-11-12,2.02,0.00777,0.00418,0.00919,-0.01326,-0.00018,0.13341,445.0,0.01,477.0,0.028,13.16,0.02,100.000000,2.0

In [39]:
train2 = df.iloc[7958:]
train2

,QUOTE_READTIME,CONTRACT,SPY PRICE,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE,PRICECLOSE,ROI %,y
7958,2021-12-14 14:00:00,477.0 2021-12-17,460.67,2021-12-17,3.08,0.02253,0.00620,0.02552,-0.04476,0.00127,0.18778,2394.0,0.07,477.0,0.035,16.33,0.18,157.142857,2.0
7959,2021-12-14 14:00:00,478.0 2021-12-17,460.67,2021-12-17,3.08,0.01790,0.00490,0.02044,-0.03482,0.00120,0.18708,1501.0,0.05,478.0,0.038,17.33,0.13,160.000000,2.0
7960,2021-12-14 14:00:00,479.0 2021-12-17,460.67,2021-12-17,3.08,0.01458,0.00408,0.01780,-0.02893,0.00081,0.18969,1322.0,0.05,479.0,0.040,18.33,0.09,80.000000,2.0
7961,2021-12-14 14:00:00,480.0 2021-12-17,460.67,2021-12-17,3.08,0.01150,0.00336,0.01452,-0.02368,0.00032,0.19173,3220.0,0.03,480.0,0.042,19.33,0.07,133.333333,2.0
7962,2021-12-14 14:00:00,481.0 2021-12-17,460.67,2021-12-17,3.08,0.01129,0.00311,0.01383,-0.02420,0.00036,0.19926,481.0,0.04,481.0,0.044,20.33,0.05,25.000000,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18281,2022-03-23 16:00:00,455.0 2022-03-25,443.84,3/25/2022,2.00,0.04696,0.01493,0.03746,-0.09216,0.00106,0.17010,12879.0,0.13,455.0,0.025,11.16,0.13,0.000000,1.0
18282,2022-03-23 16:00:00,456.0 2022-03-25,443.84,3/25/2022,2.00,0.03309,0.01144,0.02826,-0.06611,0.00075,0.16963,10707.0,0.09,456.0,0.027,12.16,0.09,0.000000,1.0
18283,2022-03-23 16:00:00,457.0 2022-03-25,443.84,3/25/2022,2.00,0.02264,0.00839,0.02085,-0.04539,0.00083,0.16879,4434.0,0.05,457.0,0.030,13.16,0.05,0.000000,1.0
18284,2022-03-23 16:00:00,458.0 2022-03-25,443.84,3/25/2022,2.00,0.01819,0.00688,0.01736,-0.03784,0.00030,0.17380,4001.0,0.04,458.0,0.032,14.16,0.04,0.000000,1.0
18285,2022-03-23 16:00:00,459.0 2022-03-25,443.84,3/25/2022,2.00,0.01514,0.00542,0.01463,-0.03065,0.00091,0.17742,2672.0,0.03,459.0,0.034,15.16,0.03,0.000000,1.0

In [40]:
train_2qs = pd.concat([train1, train2], axis=0)
train_2qs

,QUOTE_READTIME,CONTRACT,SPY PRICE,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_VOLUME,C_LAST,STRIKE,STRIKE_DISTANCE_PCT,STRIKE DISTANCE,PRICECLOSE,ROI %,y
0,2021-10-04 09:30:00,430.0 2021-10-08,432.95,2021-10-08,4.27,0.61310,0.03556,0.19356,-0.43339,0.03538,0.21263,10.0,5.93,430.0,0.007,-2.95,6.11,3.035413,1.0
1,2021-10-04 09:30:00,431.0 2021-10-08,432.95,2021-10-08,4.27,0.57914,0.03730,0.19781,-0.43196,0.03344,0.20709,1.0,5.21,431.0,0.004,-1.95,5.31,1.919386,1.0
2,2021-10-04 09:30:00,432.0 2021-10-08,432.95,2021-10-08,4.27,0.54144,0.03858,0.20139,-0.43035,0.03157,0.20271,0.0,5.61,432.0,0.002,-0.95,4.63,-17.468806,1.0
3,2021-10-04 09:30:00,433.0 2021-10-08,432.95,2021-10-08,4.27,0.50267,0.03978,0.20224,-0.42316,0.02886,0.19849,1.0,4.01,433.0,0.000,0.05,3.95,-1.496259,1.0
4,2021-10-04 09:30:00,434.0 2021-10-08,432.95,2021-10-08,4.27,0.46199,0.04063,0.20081,-0.41040,0.02677,0.19261,13.0,3.42,434.0,0.002,1.05,3.22,-5.847953,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18281,2022-03-23 16:00:00,455.0 2022-03-25,443.84,3/25/2022,2.00,0.04696,0.01493,0.03746,-0.09216,0.00106,0.17010,12879.0,0.13,455.0,0.025,11.16,0.13,0.000000,1.0
18282,2022-03-23 16:00:00,456.0 2022-03-25,443.84,3/25/2022,2.00,0.03309,0.01144,0.02826,-0.06611,0.00075,0.16963,10707.0,0.09,456.0,0.027,12.16,0.09,0.000000,1.0
18283,2022-03-23 16:00:00,457.0 2022-03-25,443.84,3/25/2022,2.00,0.02264,0.00839,0.02085,-0.04539,0.00083,0.16879,4434.0,0.05,457.0,0.030,13.16,0.05,0.000000,1.0
18284,2022-03-23 16:00:00,458.0 2022-03-25,443.84,3/25/2022,2.00,0.01819,0.00688,0.01736,-0.03784,0.00030,0.17380,4001.0,0.04,458.0,0.032,14.16,0.04,0.000000,1.0
18285,2022-03-23 16:00:00,459.0 2022-03-25,443.84,3/25/2022,2.00,0.01514,0.00542,0.01463,-0.03065,0.00091,0.17742,2672.0,0.03,459.0,0.034,15.16,0.03,0.000000,1.0

In [41]:
train_2qs.to_csv("./Resources/train_2qs.csv", index=None)
test_2qs.to_csv("./Resources/test_2qs.csv", index=None)